name: Tide Notification

on:
  schedule:
    - cron: '0 7 * * *'  # runs daily at 7 AM UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip libx11-xcb1 libnss3 libgbm-dev libasound2
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tide script
        env:
          PUSHBULLET_ACCESS_TOKEN: ${{ secrets.PUSHBULLET_ACCESS_TOKEN }}
          STATION_NAME: ${{ secrets.STATION_NAME }}
        run: python tide_notifier.py