name: Tide Notification

on:
  schedule:
    - cron: '0 7 * * *'  # runs daily at 7 AM UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            curl \
            unzip \
            libx11-dev \
            libx11-xcb1 \
            libxcomposite1 \
            libxrandr2 \
            libxss1 \
            libgdk-pixbuf2.0-0 \
            libdbus-1-3 \
            libasound2 \
            fonts-liberation \
            libappindicator3-1 \
            libnss3 \
            lsb-release \
            xdg-utils
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tide script
        env:
          PUSHBULLET_ACCESS_TOKEN: ${{ secrets.PUSHBULLET_ACCESS_TOKEN }}
          STATION_NAME: ${{ secrets.STATION_NAME }}
        run: python tide_notifier.py