name: Tide Notification

on:
  schedule:
    - cron: '0 7 * * *'  # runs daily at 7 AM UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip libx11-xcb1 libnss3 libgbm-dev gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tide script
        env:
          PUSHBULLET_ACCESS_TOKEN: ${{ secrets.PUSHBULLET_ACCESS_TOKEN }}
          STATION_NAME: ${{ secrets.STATION_NAME }}
          CI: "true"
        run: python tide_notifier.py

      - name: Upload debug artifacts
        if: always()  # even if the script fails
        uses: actions/upload-artifact@v3.1.3
        with:
          name: tide-debug
          path: |
            tide_debug.png
            page_source.html